---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: embercsis.ember-csi.io
  namespace: ember-csi
spec:
  group: ember-csi.io
  names:
    kind: EmberCSI
    listKind: EmberCSIList
    plural: embercsis
    singular: embercsi
  scope: Namespaced
  version: v1alpha1
